### ISSUE TITLE
conda_env.yml failing to install

### ISSUE THREAD

**Issue by DustinKLo** [insarlab/MintPy#171] opened 2019-08-05 17:28 UTC
When running the install command `conda env create -f /MintPy/docs/conda_env.yml` it completes at the conda level but not at the pip level. I'm getting this error below

```
Ran pip subprocess with arguments:
['/opt/conda/envs/mintpy/bin/python', '-m', 'pip', 'install', '-U', '-r', '/MintPy/docs/condaenv.xs9yxqx0.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/tylere/pykml.git (from -r /MintPy/docs/condaenv.xs9yxqx0.requirements.txt (line 2))
  Cloning https://github.com/tylere/pykml.git to /tmp/pip-req-build-u2km5mfy
Collecting mpl_toolkits from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits (from -r /MintPy/docs/condaenv.xs9yxqx0.requirements.txt (line 1))
  Cloning https://github.com/matplotlib/basemap.git to /tmp/pip-install-ssja7bok/mpl-toolkits

Pip subprocess error:
  Running command git clone -q https://github.com/tylere/pykml.git /tmp/pip-req-build-u2km5mfy
  Running command git clone -q https://github.com/matplotlib/basemap.git /tmp/pip-install-ssja7bok/mpl-toolkits
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/mintpy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ssja7bok/mpl-toolkits/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ssja7bok/mpl-toolkits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ssja7bok/mpl-toolkits/
    Complete output (18 lines):
    checking for GEOS lib in /root ....
    checking for GEOS lib in /root/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....
    
    Can't find geos library in standard locations ('/root', '/root/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed
```

How do I proceed with this error? Thanks!

**Comment by DustinKLo** [comment] 2019-08-05 17:34
i am installing it in a docker environment, specifically `continuumio/miniconda:latest`

**Comment by yunjunz** [comment] 2019-08-05 19:05
Hi @DustinKLo, I don't have experience with docker and can not tell the cause of the issue you have. I would recommend running `pip install` in the command line, within `mintpy` environment, to see what's going on in more details.

With the test I had on my laptop (with Sierra OSX) and HPC with Linux CentOS, it works fine.

**Comment by DustinKLo** [comment] 2019-08-05 19:21
@yunjunz  I tested the installation on my local computer (no docker) and im still getting the same error

```
Python 3.7.3
conda 4.7.10
```

**Comment by yunjunz** [comment] 2019-08-05 19:22
@DustinKLo, could you show me more details?

**Comment by DustinKLo** [comment] 2019-08-05 19:26
@yunjunz  i'm running this command within the `mintpy` environment

```
(mintpy) LMC-063631:Desktop dustinlo$ pip install git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
Collecting mpl_toolkits from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
  Cloning https://github.com/matplotlib/basemap.git to /private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits
  Running command git clone -q https://github.com/matplotlib/basemap.git /private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits
    ERROR: Command errored out with exit status 1:
     command: //anaconda3/envs/mintpy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits/setup.py'"'"'; __file__='"'"'/private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits/
    Complete output (18 lines):
    checking for GEOS lib in /Users/dustinlo ....
    checking for GEOS lib in /Users/dustinlo/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....
    
    Can't find geos library in standard locations ('/Users/dustinlo', '/Users/dustinlo/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by yunjunz** [comment] 2019-08-05 19:43
Hi @DustinKLo, from your error message it shown the following command failed. Unfortunately I can not replicate your error, you will need to figure it out on your own. If this did not work, try the temporary solution here: https://github.com/insarlab/MintPy/issues/83#issuecomment-500253943.

```
Running command git clone -q https://github.com/matplotlib/basemap.git /private/var/folders/0k/mc65m8wd1l7cz88pywmkc0102_jhrp/T/pip-install-3_bavyew/mpl-toolkits
```

As you can see my `basemap` installation has error too (this is a development version, thus problems are expected), but it got installed. This problem should be solved when basemap updates its conda-built version in the future.

```
[yunjunz:~] yunjunz% conda activate mintpy
(mintpy) [yunjunz:~] yunjunz% pip install git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
Collecting mpl_toolkits from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
  Cloning https://github.com/matplotlib/basemap.git to /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/mpl-toolkits
  Running command git clone -q https://github.com/matplotlib/basemap.git /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/mpl-toolkits
  WARNING: Generating metadata for package mpl-toolkits produced metadata for project name basemap. Fix your #egg=mpl-toolkits fragments.
Requirement already satisfied (use --upgrade to upgrade): basemap from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages
Requirement already satisfied: matplotlib!=3.0.1,>=1.0.0 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from basemap) (3.1.1)
Requirement already satisfied: numpy>=1.2.1 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from basemap) (1.17.0)
Requirement already satisfied: pyproj>=1.9.3 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from basemap) (2.2.1)
Requirement already satisfied: pyshp>=1.2.0 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from basemap) (2.1.0)
Requirement already satisfied: six in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from basemap) (1.12.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (2.4.2)
Requirement already satisfied: cycler>=0.10 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from matplotlib!=3.0.1,>=1.0.0->basemap) (1.1.0)
Requirement already satisfied: setuptools in ./development/python/test/miniconda3/envs/mintpy/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib!=3.0.1,>=1.0.0->basemap) (41.0.1)
Building wheels for collected packages: basemap, basemap
  Building wheel for basemap (setup.py) ... done
  Created wheel for basemap: filename=basemap-1.2.0-cp37-cp37m-macosx_10_9_x86_64.whl size=121669190 sha256=1d0d19db34220efd5ab3970a58e6fe9515f633f24afd596b755aeff3e9cff446
  Stored in directory: /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-ephem-wheel-cache-g4x8f9hd/wheels/3f/f3/56/de548b66967d0d661612b7618022e2c0d4b86b9a638cf6ccf3
  Building wheel for basemap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/yunjunz/development/python/test/miniconda3/envs/mintpy/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'"'"'; __file__='"'"'/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-wheel-e70xoaz9 --python-tag cp37
       cwd: /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/yunjunz/development/python/test/miniconda3/envs/mintpy/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for basemap
  Running setup.py clean for basemap
  ERROR: Command errored out with exit status 1:
   command: /Users/yunjunz/development/python/test/miniconda3/envs/mintpy/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'"'"'; __file__='"'"'/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Users/yunjunz/development/python/test/miniconda3/envs/mintpy/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/bg/9j3hscxn7t53s3c078rlck7c0000gq/T/pip-install-5m_hjuz3/basemap/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for basemap
Successfully built basemap
Failed to build basemap
(mintpy) [yunjunz:~] yunjunz% python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpl_toolkits import basemap
>>> 
```

**Comment by DustinKLo** [comment] 2019-08-05 19:52
@yunjunz  which anaconda version are you using?

**Comment by yunjunz** [comment] 2019-08-05 20:09
latest, same as the note on Github.

**Comment by DustinKLo** [comment] 2019-08-05 20:19
@yunjunz i think i found the root cause, i think its because my docker environment (and local mac) did not have the GCC compiler installed on it

running `apt-get install build-essential` fixed this issue

**Comment by hfattahi** [comment] 2019-08-05 20:19
Since you are using the mintpy environment I assume your pip is the one form conda. However, make sure that is the case by simply saying “which pip”

Heresh

**Comment by hfattahi** [comment] 2019-08-05 20:21
Crossing emails. Looks like you already solved the issue.

**Comment by EJFielding** [comment] 2019-08-22 23:36
I am getting the same problem trying to install on Linux computer at JPL.
`
Ran pip subprocess with arguments:
['/u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/fielding/tools/MintPy/docs/condaenv.p5ehhniu.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/tylere/pykml.git (from -r /home/fielding/tools/MintPy/docs/condaenv.p5ehhniu.requirements.txt (line 2))
  Cloning https://github.com/tylere/pykml.git to /tmp/pip-req-build-pd0pxog1
Collecting mpl_toolkits from git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits (from -r /home/fielding/tools/MintPy/docs/condaenv.p5ehhniu.requirements.txt (line 1))
  Cloning https://github.com/matplotlib/basemap.git to /tmp/pip-install-is_ajghk/mpl-toolkits

Pip subprocess error:
  Running command git clone -q https://github.com/tylere/pykml.git /tmp/pip-req-build-pd0pxog1
  Running command git clone -q https://github.com/matplotlib/basemap.git /tmp/pip-install-is_ajghk/mpl-toolkits
    ERROR: Command errored out with exit status 1:
     command: /u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-is_ajghk/mpl-toolkits/setup.py'"'"'; __file__='"'"'/tmp/pip-install-is_ajghk/mpl-toolkits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-is_ajghk/mpl-toolkits/
    Complete output (18 lines):
    checking for GEOS lib in /home/fielding ....
    checking for GEOS lib in /home/fielding/local ....
    checking for GEOS lib in /usr ....
    checking for GEOS lib in /usr/local ....
    checking for GEOS lib in /sw ....
    checking for GEOS lib in /opt ....
    checking for GEOS lib in /opt/local ....

    Can't find geos library in standard locations ('/home/fielding', '/home/fielding/local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
    Please install the corresponding packages using your
    systems software management system (e.g. for Debian Linux do:
    'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
    set the environment variable GEOS_DIR to point to the location
    where geos is installed (for example, if geos_c.h
    is in /usr/local/include, and libgeos_c is in /usr/local/lib,
    set GEOS_DIR to /usr/local), or edit the setup.py script
    manually and set the variable GEOS_dir (right after the line
    that says "set GEOS_dir manually here".
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed
`
It seems that there is a dependency on "libgeos" that is not available.

**Comment by DustinKLo** [comment] 2019-08-23 00:28
@EJFielding  i think its because you need to have a GCC compiler on your computer, as `libgeos` is a C++ library
If you're using Ubuntu, these commands worked for me when I was creating my Docker-ized version of MintPy (w/ debian base image)
```
sudo apt-get update
sudo apt-get install -y build-essential
sudo apt-get install -y libgeos-dev
```
https://github.com/DustinKLo/unavco-docker-images/blob/master/mintpy-docker/Dockerfile

**Comment by EJFielding** [comment] 2019-08-23 00:42
I don’t have root privileges on the Linux server, so I can’t install with apt-get. What version of GCC does this require?

**Comment by DustinKLo** [comment] 2019-08-23 00:50
i think the most recent version of GCC should be fine

**Comment by falkamelung** [comment] 2019-08-23 01:07
Eric,
I used to have this issue and I was able to resolve it using conda install of libgcc (and gcc). I don’t remember exactly what I used but I do see in an old file the packages below, which probably do it.
Falk

gcc-5=5.2.0
libgcc=7.2.0
libgcc-ng=7.3.0


On Aug 22, 2019, at 8:42 PM, Eric Fielding <notifications@github.com<mailto:notifications@github.com>> wrote:


I don’t have root privileges on the Linux server, so I can’t install with apt-get. What version of GCC does this require?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fissues%2F171%3Femail_source%3Dnotifications%26email_token%3DACVFHXH4IJEGYONMX4WDM5DQF4W5TA5CNFSM4IJNKLZ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD46ZJXY%23issuecomment-524129503&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C60d77bba3c164e3a594e08d72762b6d4%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637021177253877759&sdata=XPRl0mP5IaXloocqgsjzYyrOd0fQAoao%2BbWnz6P41bw%3D&reserved=0>, or mute the thread<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACVFHXHN6ZDAXQ4C76JGP5DQF4W5TANCNFSM4IJNKLZQ&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C60d77bba3c164e3a594e08d72762b6d4%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637021177253877759&sdata=yTi7pRE1UAcTSsYXN84AjPkltZdMyTuVrtGSzj95SBI%3D&reserved=0>.

------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web:http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu

**Comment by hfattahi** [comment] 2019-08-23 01:25
@EJFielding I have not been able to reproduce this issue. The error seems to be with geos, which seems to be available through conda as well:

https://anaconda.org/conda-forge/geos

**Comment by EJFielding** [comment] 2019-08-23 01:30
@hfattahi Do you have an account on Pez? That is where I am trying to install.

**Comment by hfattahi** [comment] 2019-08-23 01:30
@EJFielding Also from the last part of the error message you posted, you may check if libgeos already exist. Posting it agian:
"
or set the environment variable GEOS_DIR to point to the location where geos is installed (for example, if geos_c.h is in /usr/local/include, and libgeos_c is in /usr/local/lib, set GEOS_DIR to /usr/local)
"

**Comment by hfattahi** [comment] 2019-08-23 01:31
> @hfattahi Do you have an account on Pez? That is where I am trying to install.

No I don't. But we can take a look at it later if the suggested solutions don't work.

**Comment by EJFielding** [comment] 2019-08-23 20:04
I went back to running the installation steps separately, including the two "pip" commands. It still failed to find the libgeos, but I was able to get it to work by manually setting the environment variable that it suggests to my Conda environment root:
`setenv GEOS_DIR /u/vento-r0/ericf/packages/Anaconda/anaconda3/envs/mintpy/`

**Comment by pvh1983** [comment] 2019-09-16 19:51
> eed

I got the same error when I install basemap using pip in a Linux cluster. I was able to overcome it by doing the following installation: 

conda install -c anaconda basemap
# Fix an error related to pyproj
pip install pyproj==1.9.6
export PROJ_LIB=`python3 -c "import pyproj; print(pyproj.pyproj_datadir)"`

**Comment by yunjunz** [comment] 2020-02-04 01:41
@Ovec8hkin has replaced basemap usage with cartopy. This problem should not exist anymore. Close it.

**Closed by yunjunz** 2020-02-04 01:41 UTC
