### ISSUE TITLE
Timeseries from ARIA standard products

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#172] opened 2019-08-07 01:38 UTC
Hello,

I am trying to run the MintPy timeseries for a very basic test case data set for ARIA standard product data over Tibet (ascending track 041).
 
I went through the setup steps required in the ARIA tools time series setup workflow:
ariaDownload.py -t 041 -b ’37.5 40 87 91’ -s 20180601 -e 20181001
ariaTSsetup.py -f .products/’S1*.nc’ -d Download -nt 8
python3 prep_aria.py -s stack -d DEM/SRTM_3arcsec.dem.vrt -i incidenceAngle/20180613_20180601.vrt
smallbaselineApp.py –start modify_network
 
The MintPy processes goes through the first several steps (modify network, reference point, correct unwrap error [off], stack interferograms, invert network, correct lod [off], troposphere [off], deramp). Then, it gets 22% of the way through the “correct topography” step before throwing an error:
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1070, in <module>
    main()
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1060, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1016, in run
    self.run_topographic_residual_correction(sname)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 796, in run_topographic_residual_correction
    mintpy.dem_error.main(scp_args.split())
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 489, in main
    inps = correct_dem_error(inps, A_def)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 425, in correct_dem_error
    num_step=num_step)
  File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 308, in estimate_dem_error
    X = linalg.lstsq(A, ts, cond=1e-15)[0]
  File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/scipy/linalg/basic.py", line 1152, in lstsq
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
    a = toarray(a)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
 
Has anyone run into anything similar?
 
Thanks,
Rob

**Comment by falkamelung** [comment] 2019-08-07 02:56
Hi Rob,
Yunjun will know better, but I think this happens when the reference point is not a valid point. Did you manually select a reference point?

Yunjun,
As you know I frequently get reference point issues. We may want to add proper checks and messages for user errors.
Falk


On Aug 7, 2019, at 9:38 AM, rzinke <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am trying to run the MintPy timeseries for a very basic test case data set for ARIA standard product data over Tibet (ascending track 041).

I went through the setup steps required in the ARIA tools time series setup workflow:
ariaDownload.py -t 041 -b ’37.5 40 87 91’ -s 20180601 -e 20181001
ariaTSsetup.py -f .products/’S1*.nc’ -d Download -nt 8
python3 prep_aria.py -s stack -d DEM/SRTM_3arcsec.dem.vrt -i incidenceAngle/20180613_20180601.vrt
smallbaselineApp.py –start modify_network

The MintPy processes goes through the first several steps (modify network, reference point, correct unwrap error [off], stack interferograms, invert network, correct lod [off], troposphere [off], deramp). Then, it gets 22% of the way through the “correct topography” step before throwing an error:
File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1070, in
main()
File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1060, in main
app.run(steps=inps.runSteps, plot=inps.plot)
File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 1016, in run
self.run_topographic_residual_correction(sname)
File "/u/sarh0/rzinke/tools/MintPy/mintpy/smallbaselineApp.py", line 796, in run_topographic_residual_correction
mintpy.dem_error.main(scp_args.split())
File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 489, in main
inps = correct_dem_error(inps, A_def)
File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 425, in correct_dem_error
num_step=num_step)
File "/u/sarh0/rzinke/tools/MintPy/mintpy/dem_error.py", line 308, in estimate_dem_error
X = linalg.lstsq(A, ts, cond=1e-15)[0]
File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/scipy/linalg/basic.py", line 1152, in lstsq
a1 = _asarray_validated(a, check_finite=check_finite)
File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/scipy/_lib/_util.py", line 239, in _asarray_validated
a = toarray(a)
File "/u/sar-r0/rzinke/python/miniconda3/envs/MintPy/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
"array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

Has anyone run into anything similar?

Thanks,
Rob

**Comment by rzinke** [comment] 2019-08-07 03:06
Hi @falkamelung, thanks for the tip. I'll have to keep that in mind for the future. 
In the config file, I left all the settings at "auto": 
## 3 Reference in Space
## reference all interferograms to one common point in space
## auto - randomly select a pixel with coherence > minCoherence
mintpy.reference.yx            = auto   #[257,151 / auto]
mintpy.reference.lalo          = auto   #[31.8,130.8 / auto]
mintpy.reference.maskFile      = auto   #[filename / no], auto for maskConnComp.h5
mintpy.reference.coherenceFile = auto   #[filename], auto for avgSpatialCoh.h5
mintpy.reference.minCoherence  = auto   #[0.0-1.0], auto for 0.85, minimum coherence for auto method

**Comment by yunjunz** [comment] 2019-08-07 04:08
Hi @rzinke, the `load_data` step in smallbaselineApp.py includes generating some auxliary files, besides writing the `inputs/ifgramStack.h5` and `inputs/geometryGeo.h5`, which is done by prep_aria.py. I guess those missing files caused the error. Try to run `smallbaselineApp.py` directly. It's OKAY if the previous step has been run, the script will skip it automatically.

From the script you posted, I recommend you to download the water mask using `--mask Download` in ariaTSsetup.py, and load it while calling `prep_aria.py` too.

**Comment by yunjunz** [comment] 2019-08-07 05:09
Since your area is quite large, I would recommend you to set the following options to get a **fast** result.

```cfg
mintpy.networkInversion.weightFunc = no
mintpy.topographicResidual.pixelwiseGeometry = no
```

**Comment by rzinke** [comment] 2019-08-07 07:02
Thanks @yunjunz! For some reason the water mask fixed it. I got a valid-looking result, though some of my parameters might have been slightly different. 
![velocity](https://user-images.githubusercontent.com/48299159/62601596-94ada280-b8a6-11e9-9551-2fc6f80f3b26.png)

**Comment by dbekaert** [comment] 2019-08-07 15:06
@yunjunz if the problem is missing files because of the first step, perhaps add the first step to be ran as one of the final lines in the aria_prep program for now untill it has been merged in to load_data?

**Comment by hfattahi** [comment] 2019-08-07 16:32
I don't think if that should be part of prep_aria. Actually preo_aria extracts the water mask and stores in inputs/geometryGeo.h5. However, for some reason smallbaselineApp.py doesn't care about the water mask in geometryGeo.h5 and rather is looking for a file called waterMask.h5. 
In the notebook I'm preparing, I create the required files after prep_aria and before inversion. 
Perhaps this could be done by smallbaslineApp.py

**Comment by yunjunz** [comment] 2019-08-07 16:43
I am still not clear what's the exact cause of the initial error that Rob had. From these commands, no water mask was involved, thus, it should work by running `smallbaselineApp.py --start modify_network`. I am testing it right now following the exact commands. 

@hfattahi, within the `load_data` step, smallbaselineApp.py extract waterMask from inputs/geometry*.h5 file and save it to waterMask.h5. This makes a lot of things easier in the code.

I agree with @hfattahi. One could run `smallbaselineApp.py` directly without specifying start/end steps, which is easier. The **auto skipping** strategy in smallbaselineApp.py could skip the unnecessary steps very well.

**Comment by hfattahi** [comment] 2019-08-07 16:53
I see. If that is the case then we should add the following to prep_aria.py:
1- create waterMask.h5
2- create avergaeSpatialCoherence.h5
3- create unwrapping common mask (maybe?)

I generate all these manually after running prep_aria. If load_data automatically takes care of them then we shoul have them in prep_aria.py.

**Comment by yunjunz** [comment] 2019-08-07 19:44
smallbaselineApp.py, within `load_data` step, do:

1) calls `load_data.py` to write inputs/ifgramStack.h5 and geometryGeo.h5, which is done by prep_aria.py in this case;
2)  extracts waterMask dataset from inputs/geometyGeo.h5 file to waterMask.h5. 

I will move 2) out of `load_data` step, so that `smallbaselineApp.py --dostep load_data` is equivalent to `load_data.py` and `prep_aria.py`. 

All auxliary files, including avgSpatialCoh.h5 and maskConnComp.h5 should be generated right before the first time they are used, I will adjust smallbaselineApp.py accordingly.

**Comment by hfattahi** [comment] 2019-08-07 20:23
Thanks @yunjunz . That will be a clean implementation and will ensure consistency between MintPy's native load_data and prep_aria.

**Comment by yunjunz** [comment] 2019-08-07 20:27
The initial error that @rzinke had is caused by the inconsistent invalid pixels between ifgramStack.h5 (which propagated to time-series) and incidenceAngle. The original dem_error.py did not appreciate the NaN value from geometry, which was a bug, it is fixed now. Thank you @rzinke for finding it out!

**Closed** 2019-08-07 23:09 UTC
