### ISSUE TITLE
`pip -e` installed `mintpy.__file__ = None` when there is a `mintpy` folder in current dir

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#882] opened 2022-11-02 03:50 UTC
**Description of the problem**

For `mintpy` installed in the editable mode using `pip`, when there is a folder named `mintpy` in the current data directory, Python would misidentify the `mintpy` folder as the module location; and result in a `TypeError` while running, as shown in the example commands below. Any idea how to fix this?

This only happens when mintpy is installed via `pip install -e` option; while regular `pip install` and `conda install` versions work fine.

**Full script that generated the error**

```
(insar) yunjunz:~/data/test/FernandinaSenDT128/mintpy>$ python -c "import mintpy; print(mintpy.__file__, mintpy.__path__)"
(insar) yunjunz:~/data/test/FernandinaSenDT128>$ python -c "import mintpy; print(mintpy.__file__, mintpy.__path__)"
(insar) yunjunz:~/data/test/FernandinaSenDT128>$ view.py mintpy/velocity.h5 
```

**Full error message**

```
(insar) yunjunz:~/data/test/FernandinaSenDT128/mintpy>$ python -c "import mintpy; print(mintpy.__file__, mintpy.__path__)"
/Users/yunjunz/tools/MintPy/mintpy/__init__.py ['/Users/yunjunz/tools/MintPy/mintpy']

(insar) yunjunz:~/data/test/FernandinaSenDT128>$ python -c "import mintpy; print(mintpy.__file__, mintpy.__path__)"
None _NamespacePath(['/Users/yunjunz/data/test/FernandinaSenDT128/mintpy', '/Users/yunjunz/data/test/FernandinaSenDT128/mintpy'])

(insar) yunjunz:~/data/test/FernandinaSenDT128>$ view.py mintpy/velocity.h5 
Traceback (most recent call last):
  File "/Users/yunjunz/tools/miniconda3/envs/insar/bin/view.py", line 8, in <module>
    sys.exit(main())
  File "/Users/yunjunz/tools/MintPy/mintpy/cli/view.py", line 166, in main
    from mintpy.view import viewer
  File "/Users/yunjunz/tools/MintPy/mintpy/view.py", line 26, in <module>
    from mintpy.utils import plot as pp, ptime, readfile, utils as ut
  File "/Users/yunjunz/tools/MintPy/mintpy/utils/plot.py", line 22, in <module>
    from mintpy.objects.colors import ColormapExt
  File "/Users/yunjunz/tools/MintPy/mintpy/objects/colors.py", line 24, in <module>
    MINTPY_CPT_DIR = os.path.join(os.path.dirname(mintpy.__file__), 'data', 'colormaps')
  File "/Users/yunjunz/tools/miniconda3/envs/insar/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**System information**

* Operating system: macOS
* Python environment: conda for dependencies, pip for mintpy
* MintPy version: 1.4.1-29, date 2022-10-31

**Comment by scottstanie** [comment] 2022-11-02 15:17
Thanks for figuring out that the empty directory was the cause of this; I had this pop up a couple months ago and was baffled, but it seemed to go away (probably when I changed directories lol).

Apparently this is from the newish [namespace package](https://docs.python.org/3/glossary.html#term-namespace-package), which I found out from this https://stackoverflow.com/questions/49082100/python-importing-empty-folder

It says [in the PEP 420](https://peps.python.org/pep-0420/) that
>  While looking for a module or package named “foo”, for each directory in the parent path:
>  - If `<directory>/foo/__init__.py `is found, a regular package is imported and returned.
>  - If not, but <directory>/foo.{py,pyc,so,pyd} is found, a module is imported and returned. The exact list of extension varies by platform and whether the -O flag is specified. The list here is representative.
>  - If not, but <directory>/foo is found and is a directory, it is recorded and **the scan continues with the next directory in the parent path.**
>  - Otherwise the scan continues with the next directory in the parent path.

(emphasis mine on the 3rd bullet).


I think the fix would be related to how mintpy is installed... I don't immediately see what is different, but for some reason the MintPy folder is not on my `sys.path`, unlike all the other packages that I used `pip install -e` on:
```ipython
In [1]: import sys; sys.path
Out[1]:
['/Users/staniewi/miniconda3/envs/mapping/bin',
 '/Users/staniewi/repos/isce2/install/packages',
 '/Users/staniewi',
 '/Users/staniewi/repos/pyre/install/packages',
 '/Users/staniewi/repos/isce3/install/packages',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python310.zip',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python3.10',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/lib-dynload',
 '',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/GDAL-3.5.0-py3.10-macosx-11.0-arm64.egg',
 '/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/PyQt5_sip-12.9.0-py3.10-macosx-11.0-arm64.egg',
 '/Users/staniewi/repos/dolphin/src',
 '/Users/staniewi/repos/s1-reader/src',
 '/Users/staniewi/repos/tophu/src',
 '/Users/staniewi/repos/unwrap-conncomp/src',
 '/Users/staniewi/repos/sardem',
...
```

So since these packages like `sardem` are on my pythonpath, this empty directory problem doesnt happen for them:
```ipython

In [1]: !mkdir sardem
In [2]: import sardem; print(sardem.__file__, sardem.__path__)
/Users/staniewi/repos/sardem/sardem/__init__.py ['/Users/staniewi/repos/sardem/sardem']
```

Sorry I don't have an immediate fix; I just see that something about Mintpy's install is different than `sardem`, `tophu`, etc, that makes it not appear on sys.path

**Comment by scottstanie** [comment] 2022-11-02 17:24
I did a little more poking around and figured out that this can be solved by adopting a `src/` layout... but I'm not sure which sounds more painful to you:
1. reorder the mintpy code structure to [use a src/ layout](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#src-layout)
2. tell people not to create a `mintpy/` folder where you are running mintpy things with an editable install

I got this by seeing that the `asfsmd` package also has the same issue as mintpy, and it just uses a single file (no src/ directory).

For both mintpy and asfsmd, the editable install makes a `.pth` file, which just calls an import for another weird python file
```console
$ ls -1 /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__*
/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.asfsmd-1.0.0.pth
/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.dolphin-0.1.dev93+g06efad8.pth
/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.mintpy-1.4.1.pth
...
/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable___asfsmd_1_0_0_finder.py
/Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable___mintpy_1_4_1_finder.py
```

mintpy and asfsmd just have this in their `.pth` files
```
$ cat /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.mintpy-1.4.1.pth
import __editable___mintpy_1_4_1_finder; __editable___mintpy_1_4_1_finder.install()
$ cat /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.asfsmd-1.0.0.pth
import __editable___asfsmd_1_0_0_finder; __editable___asfsmd_1_0_0_finder.install()
```

whereas the packages with a `src/` layout point to the actual path, and so they get put on the `sys.path`

```console
$ cat /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/__editable__.dolphin-0.1.dev93+g06efad8.pth
/Users/staniewi/repos/dolphin/src
```


I thought this was a setuptools bug, but if you install with `-vvv`, you get...
```console
(mapping) staniewi:MintPy$  pip install -e . -vvv --disable-pip-version-check
Using pip 22.1.2 from /Users/staniewi/miniconda3/envs/mapping/lib/python3.10/site-packages/pip (python 3.10)

....(lots of printing)

  /private/var/folders/hw/sj9hl8555s36n00t812twvcr0000gq/T/pip-build-env-hhn91hsn/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py:510: InformationOnly:

          Please be careful with folders in your working directory with the same
          name as your package as they may take precedence during imports.

    warnings.warn(msg, InformationOnly)
```
so I think they would close this issue if we brought it up there.

**Comment by jhkennedy** [comment] 2022-11-02 17:31
@scottstanie I think a `src` layout is the approach here. I'd be happy to open a PR; shouldn't be too huge of a lift.

**Comment by yunjunz** [comment] 2022-11-02 17:43
Thank you @scottstanie for figuring out the solution! I agree with @jhkennedy that the `src` layout is perfectly fine, this gives us the motivation to switch also. @jhkennedy please feel free to open a PR for this.

**Comment by yunjunz** [comment] 2022-11-08 19:38
Given the approaching of AGU, I would like to do this big change sooner than later. @jhkennedy if you have not started on this yet, I could take over and issue a PR soon. Let me know please.

**Comment by jhkennedy** [comment] 2022-11-08 20:32
@yunjunz The week got away from me last week and I didn't do anything significant to start it. Feel free to start it and I'll happily review it. Or I should be able to get to it later this week.

**Closed** 2022-11-09 21:14 UTC
Labels: bug
