### ISSUE TITLE
circle CI: test failed during PR but passed after merging

### ISSUE THREAD

**Issue by yunjunz** [insarlab/MintPy#401] opened 2020-07-16 19:13 UTC
**Description of the problem**

The circle CI build_and_test workflow has been in operation for over a month and works most of the time (big thanks to you @mehdizadehm!). There are a few anomalies.

#388 passed [test during PR](https://app.circleci.com/pipelines/github/insarlab/MintPy/428/workflows/ea37e498-6ab9-4eae-9ab7-e7cf4bd8d34d/jobs/456/steps) and failed [test after merging to the master branch](https://app.circleci.com/pipelines/github/insarlab/MintPy/429/workflows/1879be2d-3341-4b70-b614-8c78aca432aa/jobs/457/steps). From the local testing on my laptop, this PR introduced a bug into the code, so our testing during the PR should have identified it.

I fixed this bug in the next PR #389, which failed the [test during the PR](https://app.circleci.com/pipelines/github/insarlab/MintPy/431/workflows/29d6dcbe-ac47-4018-966d-4123c0a1d1bf/jobs/459) and passed the [test after merging](https://app.circleci.com/pipelines/github/insarlab/MintPy/432/workflows/e35d8e69-c7cc-49aa-8126-eeed8e82b34f/jobs/460/steps).

Similarly in another PR #393, the test [failed during PR](https://app.circleci.com/pipelines/github/insarlab/MintPy/437/workflows/8420c2fc-0cea-4693-805e-b5b7e116faa9/jobs/465/steps) and [passed after merging](https://app.circleci.com/pipelines/github/insarlab/MintPy/438/workflows/83cac343-c715-488b-b0d9-986e76c027d0/jobs/466/steps). In this PR, I changed code/settings related to the testing script. Whereas the above PRs are bugs introduction/fixing related.

**Possible causes**

These behaviors indicate that circle CI is using the code from the default branch for testing during PR, where it should use the code from the PR. It will be good to know why these happen and if it's fixable.

Here (https://ideas.circleci.com/ideas/CCI-I-316) is what I found from a quick search.

**Comment by mehdizadehm** [comment] 2020-07-18 17:23
The issue is my funny mistake.

We don't use the default CircleCI command "Check Out" to get the latest changes in our branch/PR (although we have this command in config file), but our own git clone command from the Installation Guidelines:

git clone https://github.com/insarlab/MintPy.git $MINTPY_HOME

So, we always clone codes from the main repository master branch, not the PR. In this way we usually test the last PR, which is already merged to master, not the current open PR.

**Comment by mehdizadehm** [comment] 2020-07-20 17:54
I just fixed and pushed the CricleCI config file, should work as expected.

**Closed** 2020-07-20 18:47 UTC
Labels: bug
