### ISSUE TITLE
FileExistsError: NO two *.prm files found! for prep_gmtsar.py 

### ISSUE THREAD

**Issue by laxmangeo** [insarlab/MintPy#1199] opened 2024-05-22 10:25 UTC
Hi, Sir,
         when I run prep_gmtsar.py below error has came 
![1_mintpy](https://github.com/insarlab/MintPy/assets/127308214/351fc1d7-73bf-4e59-8310-8e3f400048dc)
my directory structure is
E:\GMTSAR1\joshimath\intf_all
├── geometry
│   └── topo_ll.grd
├── intf_all
│   ├──2021009_2021021
│   │   ├── S1_20210110_ALL_F3.LED
│   │   ├── S1_20210110_ALL_F3.PRM
│   │   ├── S1_20210122_ALL_F3.LED
│   │   ├── S1_20210122_ALL_F3.PRM
│   │   ├── baseline.txt  
│   │   ├── corr.grd
│   │   ├── corr_ll.grd
│   │   ├── unwrap.grd
│   │   └── unwrap_ll.grd
│   ├── 2021009_2021033
│   └── ...
└── mintpy
    └──timeseries.txt
please suggest me

**Comment by soroushyasini** [comment] 2024-05-26 09:08
hi, I've encountered this error before. I believe you should rename *.LED and *.PRM files like this :
20210110.LED, 20210110.PRM and so on

**Comment by laxmangeo** [comment] 2024-05-27 06:19
Hi,
I was renamed files like 20210110.LED, 20210110.PRM
after i ran prep_gmtsar.py i got the new error 
![prep_mitpy](https://github.com/insarlab/MintPy/assets/127308214/cf8bbeb1-a4c3-4d77-83f0-c73da9df7818)

**Comment by soroushyasini** [comment] 2024-05-27 12:43
I did not know this issue since I've never encountered it. but i think perhaps it's related to the config file. can you provide me the config file specially the part for setting GMTSAR data path ?

**Comment by soroushyasini** [comment] 2024-05-27 12:45
also we can check baseline.txt file, can you provide one of them here ?

**Comment by laxmangeo** [comment] 2024-05-28 05:10
yes you are right , this issue from baseline.txt , i solved it , but 
![prep_mintpy1](https://github.com/insarlab/MintPy/assets/127308214/94b2d9b5-e4f6-4acf-b1ef-ab0365f04052)
TypeError: Can't broadcast (410, 350) -> (390, 330)

**Comment by soroushyasini** [comment] 2024-05-28 20:32
happy to see that you solve them and yet here are new problems to solve :)
this issue is exactly the same issue I am struggling with it , check this link below :

https://github.com/gmtsar/gmtsar/issues/921

i checked each unwrap_ll and corr_ll files that GMTSAR created, are slightly different in term of pixel size and X,Y dimension.
and that is why Mintpy can not make a array of rasters since it need same-sized rasters as input.
as far as i know, the problem is because of GMTSAR and not for Mintpy.
by the way, i am glad if you find any solution and share it to me.

**Comment by laxmangeo** [comment] 2024-05-31 05:20
have you used any region cut at the time of unwrapping? in my case I did that, Now I tried region cut at the generation of interferograms ( batch_tops.config file), problem was solved.

**Comment by soroushyasini** [comment] 2024-05-31 19:29
no i did not cut them. interesting... so did you cut by lat/long or by radar coordinates ?
and second question, how did you run gmtsar? i mean did you use batch_processing.csh ?

**Comment by laxmangeo** [comment] 2024-06-03 04:42
I cut in radar coordinates, I'm using batch_processing.csh

**Comment by soroushyasini** [comment] 2024-06-03 06:20
ok I got it, thanks for your help.
i guess this issue can be closed as Completed.

**Closed** 2024-06-03 09:14 UTC
