### ISSUE TITLE
geocoding default posting not right

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MintPy#762] opened 2022-04-20 04:43 UTC
**Description of the problem**
The default geocoding posting has too coarse posting. This seems to have been introduced by a recent PR (see below). If you click on the left image, you will clearly see the too coarse posting. The right (old) one is fine.

April 2022 version (current)
```
info.py single_reference_network/geo/geo_velocity.h5 | grep STEP
  X_STEP                                         0.001091196487729643
  Y_STEP                                         -0.000745487944481714
```
August 2021 version
```
info.py old_single_reference_network/geo/geo_velocity.h5 | grep STEP
  X_STEP                                         0.00005.620652502709693
  Y_STEP                                         -0.0001444254166040665
```
| April 2022 version| August 2021 version |
| ------------- | ------------- |
|<img width="500" alt="image" src="https://user-images.githubusercontent.com/11162588/164150047-3cb28854-1f8a-439b-993d-28c772197cc5.png">|<img width="500" alt="image" src="https://user-images.githubusercontent.com/11162588/164150298-438ce054-614b-4b47-b7ca-185cb6379b31.png">|

I see that in this PR `https://github.com/insarlab/MintPy/pull/722/commits/e44ee4cf8e6950d7771728e25067d8f3aca02174` the calculation of the posting sampling got changed, which could be the culprit
https://github.com/insarlab/MintPy/pull/722/commits/e44ee4cf8e6950d7771728e25067d8f3aca02174

As an aside, for a lower-spatial resolution case (more looks) the difference is smaller. I am not sure whether this is "good luck" and/or whether this this problem only occurs for high resolution.

**Comment by yunjunz** [comment] 2022-04-21 04:10
Hi @falkamelung, it seems that the auto step calculation based on the metadata `AZIMUTH/RANGE_PIXEL_SIZE` is not correct, could you check these two in your dataset, to confirm they are reasonable?

If yes, then could you share the `velocity.h5` and `geometryRadar.h5` files for me to reproduce this issue?

**Comment by falkamelung** [comment] 2022-04-21 04:43
Hi @yunjunz ,
Yes, you are right!  The *_PIXEL_SIZE fields have been multiplied by the number of looks. This is a MiaplPy issue.  Maybe  @mirzaees  has a solution?

info.py /scratch/05861/tg851601/StHelensSenAT137/minopy/inputs/geometryRadar.h5 | grep PIXEL_SIZE
  AZIMUTH_PIXEL_SIZE        93.62983128118586
  RANGE_PIXEL_SIZE          55.90949075316776
//login3/scratch/05861/tg851601/StHelensSenAT137[1034] info.py /scratch/05861/tg851601/StHelensSenAT137/minopy/inputs/slcStack.h5 | grep PIXEL_SIZE
  AZIMUTH_PIXEL_SIZE        93.62983128118586
  RANGE_PIXEL_SIZE          55.90949075316776

Thank you!

**Comment by yunjunz** [comment] 2022-04-28 22:47
Close this issue as the cause has been identified and is outside of mintpy.

**Closed by yunjunz** 2022-04-28 22:47 UTC
Labels: bug
