### ISSUE TITLE
UAVSAR: Track's segments have the same geometry information

### ISSUE THREAD

**Issue by nicodalse** [insarlab/MintPy#407] opened 2020-07-21 01:15 UTC
I'm trying to analyse the SanAnd_14003_01 track (it's split in 4 segments) .Seems like it's not getting the correct imaging geometry information for the different segments. Infact all the .kmz and .grd files from the other 4 segments have the coordinates of segment 1. (Those files come from smallbaslineApp.py, I attached below the .txt used for the segment 2) 
```
isce.processor          = stripmapStack  #[stripmapStack, topsStack]
#isce.demSNWE            = 31, 33, 130, 132  #[S, N, W, E] in degree
isce.demFile            = /u/aa/seno/UAVSAR/SanAnd_14003_01_s1/CentralCali_TDX.dem.wgs84
isce.azimuthLooks       = 8
isce.rangeLooks         = 2
isce.maxTempBaseline    = 600
isce.maxPerpBaseline    = 200
isce.unwrapMethod       = snaphu
isce.filtStrength       = 0.2
isce.applyWaterMask     = yes


##------------------------------- mintpy OPTIONS -------------------------------##
## load_data.py -H to check more details and example inputs.
mintpy.load.processor        = isce
##---------for ISCE only:
mintpy.load.metaFile         = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/Igrams/*/masterShelve/data.dat
mintpy.load.baselineDir      = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/baselines
##---------interferogram datasets:
mintpy.load.unwFile          = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/Igrams/*/filt_*.unw
mintpy.load.corFile          = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/Igrams/*/filt_*.cor
mintpy.load.connCompFile     = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/Igrams/*/filt_*.unw.conncomp
##---------geometry datasets:
mintpy.load.demFile          = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/hgt.rdr
mintpy.load.lookupYFile      = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/lat.rdr
mintpy.load.lookupXFile      = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/lon.rdr
mintpy.load.incAngleFile     = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/los.rdr
mintpy.load.azAngleFile      = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/los.rdr
mintpy.load.shadowMaskFile   = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/shadowMask.rdr
mintpy.load.waterMaskFile    = /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/geom_master/waterMask.rdr
mintpy.load.bperpFile        = None

#mintpy.reference.lalo          = 31.73, 131.07
mintpy.network.coherenceBased   = yes
mintpy.network.keepMinSpanTree  = auto  #[yes / no], auto for yes, keep interferograms in Min Span Tree network
mintpy.network.minCoherence     = 0.2
mintpy.troposphericDelay.method = no  #[pyaps / height_correlation / no], auto for pyaps
mintpy.deramp                   = linear
mintpy.network.tempBaseMax = 300
```
`MintPy release version v1.2.3, release date 2020-07-14`

**Comment by yunjunz** [comment] 2020-07-21 04:15
Hi @nicodalse, I don't have experience in processing UAVSAR data with stripmapStack. @taliboliver has written some scripts to prepare the output of stripmapStack if I understand it right. I recommend you to contact him.

**Comment by nicodalse** [comment] 2020-08-01 01:50
I have contact @taliboliver but unfortunately he have no experience processing split segments of UAVSAR. He also tried to help me to change the `isce.demSNWE` parameter, but the result is still the same (all 4 segments are located with coordinates of the first one). Seems there are some troubles with the segments that aren't the first one.

I attached also below my ISCE processing steps:

- prepareUAVSAR_coregStack.py -i downloadHH -o SLC -d SanAnd_14003_01_BC.dop -s 2 ( ’-segment 2’ this last flag is the only thing that I change for each segment)

- stackStripMap.py -s SLC/ -d CentralCali_TDX.dem.wgs84 -a 8 -r 2 -W interferogram --nofocus -S uavsar_stack -t 600 --filter_strength 0.2

- ./run-igrams.tcsh (nohup source /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/run_files/run_8_igram > igrams.log)

- ./run-master.tcsh (nohup source /u/aa/seno/UAVSAR/SanAnd_14003_01_s2/run_files/run_1_master > master.log)

- smallbaselineApp.py .txt

**Comment by yunjunz** [comment] 2020-08-01 22:52
Hi @nicodalse, I can not tell what's the cause of the issue here since I don't know what's a segment for UAVSAR and how the data file organized for it. For each segment, do all the output interferogram data and geometry data from stripmapStack look right to you? Both `$ISCE_HOME/applications/mdx.py` and `$MINTPY_HOME/mintpy/view.py` could plot them.

If yes for the above question, then it should be caused in the mintpy stage; then I could check more if you could send me a sample dataset.

**Comment by piyushrpt** [comment] 2020-08-01 23:36
The problem is very likely due to incomplete integration of uavsar in stripmapStack by the contributors. The default segment index is one. The contributors probably are only working with one segment and did not test for the general cases. You can add the option to add segment index to unpackFrame and continue from there. 

https://github.com/isce-framework/isce2/blob/b13d06aa3b981119d32c9da7dd1bb244622bed1e/components/isceobj/Sensor/UAVSAR_Stack.py#L57-L64

**Comment by EJFielding** [comment] 2020-08-02 23:33
@piyushrpt Thanks for pointing to the Sensor code for the  UAVSAR_Stack. That must be the problem.

**Comment by piyushrpt** [comment] 2020-08-03 00:07
The problem is in the prepareUAVSAR_coregStack.py and not the sensor reader. The segment number is not propagated to the reader at all in that script.

**Comment by yunjunz** [comment] 2020-10-13 19:33
The issue has been fixed in https://github.com/isce-framework/isce2/pull/171.

**Closed by yunjunz** 2020-10-13 19:33 UTC
