### ISSUE TITLE
ARIA products not loading properly

### ISSUE THREAD

**Issue by rzinke** [insarlab/MintPy#453] opened 2020-10-04 20:22 UTC
**Description of the problem**
When I try to load ARIA standard products into MintPy, then view the products, the maps come up blank. Specifically, 
```
view.py inputs/ifgramStack.h5 
```
yields this:
![unwrapPhase_1](https://user-images.githubusercontent.com/48299159/95026071-817d9a80-0643-11eb-89cd-f8a428f5421f.png)

The error first came to my attention when running smallbaselineApp.py and the reference point did not have any valid pixels, despite being in a stable region. I checked the maskConnComp and it was all zeros. The avgSpatCoh.h5 file is all zero as well. However, when I check the /unwrappedPhase outputs of ariaTSsetup.py, the inteferograms all look valid.

The prep_aria.py script appeared to run properly. Am I missing a step?

**System information**

* Operating system: Linux-CentOS
* Python environment: conda
* Version of MintPy: MintPy release version v1.2.3-49, release date 2020-10-01
* Version of ARIA-tools: commit c8fd3ca8cefe76f77d913299c66af6347e6688f5

Parameters file attached
[Parameters19A.txt](https://github.com/insarlab/MintPy/files/5324283/Parameters19A.txt)

**Comment by yunjunz** [comment] 2020-10-04 21:09
Hi @rzinke, to help diagnose, could you remove the `inputs` folder and re-run `prep_aria.py`, paste the printout msg here, and show one plot of view.py for /unwrappedPhase and /inputs/ifgramStack.h5?

**Comment by rzinke** [comment] 2020-10-04 22:10
Hi @yunjunz, I removed the ```inputs``` folder and all .h5 files. I reran ```prep_aria.py```

```
python3 prep_aria.py -s stack/ -d DEM/SRTM_3arcsec.dem.vrt -i incidenceAngle/20150204_20141218.vrt -a azimuthAngle/20150204_20141218.vrt --water-mask mask/watermask.msk.vrt
```

The printout is as follows:

```
update mode: OFF
extract metadata from /u/sar-r2/rzinke/Tibet/T19_FullTrack_aria/19_A_Tibet/ML3/stack/unwrapStack.vrt
--------------------------------------------------
create HDF5 file ./inputs/ifgramStack.h5 with w mode
create dataset: date                      of |S8                       in size of (362, 2)
create dataset: dropIfgram                of <class 'numpy.bool_'>     in size of (362,)
create dataset: bperp                     of <class 'numpy.float32'>   in size of (362,)
create dataset: unwrapPhase               of <class 'numpy.float32'>   in size of (362, 3426, 2025)
create dataset: coherence                 of <class 'numpy.float32'>   in size of (362, 3426, 2025)
create dataset: connectComponent          of <class 'numpy.int16'>     in size of (362, 3426, 2025)
close  HDF5 file ./inputs/ifgramStack.h5
--------------------------------------------------
opening unwrapStack.vrt, cohStack.vrt, connCompStack.vrt with gdal ...
grab NoDataValue for unwrapPhase:      0.0   and convert to 0.
grab NoDataValue for coherence:        0.0   and convert to 0.
grab NoDataValue for connectComponent: -1.0  and convert to 0.
writing data to HDF5 file ./inputs/ifgramStack.h5 with a mode ...
[==================================================] 20200315_20200327  799s /    16s
finished writing to HD5 file: ./inputs/ifgramStack.h5
--------------------------------------------------
create HDF5 file ./inputs/geometryGeo.h5 with w mode
create dataset: height                    of <class 'numpy.float32'>   in size of (3426, 2025)
create dataset: incidenceAngle            of <class 'numpy.float32'>   in size of (3426, 2025)
create dataset: slantRangeDistance        of <class 'numpy.float32'>   in size of (3426, 2025)
create dataset: azimuthAngle              of <class 'numpy.float32'>   in size of (3426, 2025)
create dataset: waterMask                 of <class 'numpy.bool_'>     in size of (3426, 2025)
close  HDF5 file ./inputs/geometryGeo.h5
--------------------------------------------------
writing data to HDF5 file ./inputs/geometryGeo.h5 with a mode ...
finished writing to HD5 file: ./inputs/geometryGeo.h5
--------------------------------------------------
```

Here is the plot from ```view.py unwrappedPhase/20200127_20200115``` (the ENVI format file). 

![20200127_20200115](https://user-images.githubusercontent.com/48299159/95028183-47b49000-0653-11eb-8e56-c75462c29adb.png)

Evidently it is all blank. This is strange because the corresponding .png has a perfectly good-looking interferogram.

Here is the first of three plots from ```view.py inputs/ifgramstack.h5```

![unwrapPhase_1](https://user-images.githubusercontent.com/48299159/95028195-61ee6e00-0653-11eb-9d6a-df58d781884d.png)

I checked my ```ariaTSsetup.py``` script and I don't know anything that could be causing this (see attached), especially given that all the .png previews look fine.

[LaunchTSsetup.txt](https://github.com/insarlab/MintPy/files/5324489/LaunchTSsetup.txt)

**Comment by yunjunz** [comment] 2020-10-05 00:42
hmm... the `view.py unwrappedPhase/20200127_20200115` plot does not look right, could you confirm the correctness of the binary data file in other independent way? using $ISCE_HOME/applications/mdx.py, or read/plot yourself?

**Comment by rzinke** [comment] 2020-10-05 16:58
Okay, I opened the same file using GDAL in Python:

![MapShow20200127_20200115](https://user-images.githubusercontent.com/48299159/95108724-7d5b8680-06f0-11eb-8cb5-0309ec27d3be.png)

It shows all zeros. This is true of many of the files in the ARIA "stack" directory. However, the .png of that same image, output by ARIA-tools, looks like this:

![20171208_20171114](https://user-images.githubusercontent.com/48299159/95109328-50f43a00-06f1-11eb-9d15-d72c281769a9.png)

**Comment by dbekaert** [comment] 2020-10-05 17:15
@rzinke The vrts point to the individual envi files. Does the envi file and
the associated png file have the same time-stamp associated? Suggest you
open an issue ticket on ARIA-tools linking to this ticket here.

**Comment by rzinke** [comment] 2020-10-05 17:19
Hi @dbekaert, yes, the all have the same time stamp. When I open the .vrt using python gdal it gives the same result. I'll open a ticket in ARIA-tools.

**Comment by yunjunz** [comment] 2020-10-05 17:51
From the shape of the png file, it seems like there might also have an issue while multilooking.

**Comment by rzinke** [comment] 2020-10-05 18:00
I think the extra white space in the upper half of the png file results from the processed frames not filling up the whole bbox that I specified in ARIA-tools.

**Comment by yunjunz** [comment] 2020-10-13 19:31
The cause of this issue (GDAL versions > 3.0.4 may generate empty outputs) is identified in https://github.com/aria-tools/ARIA-tools/pull/234 and has been handled in https://github.com/aria-tools/ARIA-tools/pull/235. Close it.

**Closed by yunjunz** 2020-10-13 19:31 UTC
