### ISSUE TITLE
pyaps: scipy.RGI reports error "The points in dimension 1 must be strictly ascending" when the grid file passing 0 longitude

### ISSUE THREAD

**Issue by ranneylxr** [insarlab/MintPy#447] opened 2020-09-24 06:25 UTC
**Description of the problem**
The sscipy.RegularGridInterpolator (tropo_pyaps3.py) reports error" The points in dimension 1 must be strictly ascending" when calculating delay using grid file passing 0 longitude.

I am trying to calculate the troposhere delay for the area covering [37N-41N; 10W-10E]. When pyaps3 tried to calculate the delay, it reported an error that " The points in dimension 1 must be strictly ascending". I checked it and found this error occurred because the lonlist calculated by Pyaps3 is [350.  , 350.25, 350.5 , ...,   9.5 ,   9.75,  10].

I wonder if there is any solutions for this error? Or there are some options in MinPy that can handle this situation? Or I have to write something to deal with this error?

Thank you very much!

**Full script that generated the error**
```
The related scritps are: tropo_pyaps3.py + pyaps3/objects.py: 
```

**Full error message**
```
Traceback (most recent call last):
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 738, in <module>
    main(sys.argv[1:])
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 710, in main
    calculate_delay_timeseries(inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 641, in calculate_delay_timeseries
    tropo_data[i] = get_delay(grib_file, inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 583, in get_delay
    aps_obj.getdelay(pha)
  File "/home/lxr/software/rsmas_insarV2/3rdparty/PyAPS/pyaps3/objects.py", line 266, in getdelay
    if self.verb:
  File "/home/lxr/software/rsmas_insarV2/3rdparty/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2444, in __init__
    "ascending" % i)
ValueError: The points in dimension 1 must be strictly ascending
```

**System information**

* Operating system:Linux-CentOS
* Python environment: conda,
* Version of MintPy: v1.2.2-65

**Comment by yunjunz** [comment] 2020-09-26 04:46
Hi @ranneylxr, I don't quite get what you mean to reproduce the error you have. Could you provide more info? [Here](https://github.com/insarlab/MintPy/issues/398) is a good example with enough info.

**Comment by ranneylxr** [comment] 2020-10-11 03:14
Hi @yunjunz.
The commond I used is:
tropo_pyaps3.py -f timeseries_demErr.h5 -g ../inputs/geometryRadar.h5

The full output is:
 weather model: ERA5 - dry (hydrostatic) and wet delay
weather directory: /data/lxr/insarlab/WEATHER
output tropospheric delay file: ../inputs/ERA5.h5
output corrected time-series file: timeseries_demErr_ERA5.h5
read dates/time info from file: timeseries_demErr.h5
time of cloest available product: 18:00 UTC

------------------------------------------------------------------------------
downloading weather model data using PyAPS ...
common file size: 1478520 bytes
number of grib files existed    : 251
number of grib files to download: 1
------------------------------------------------------------------------------

INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
Downloading 1 of 1: /data/lxr/insarlab/WEATHER/ERA5/ERA5_N30_N50_W10_E10_20160316_18.grb
{'product_type': 'reanalysis', 'format': 'grib', 'variable': ['geopotential', 'temperature', 'specific_humidity'], 'pressure_level': ['1', '2', '3', '5', '7', '10', '20', '30', '50', '70', '100', '125', '150', '175', '200', '225', '250', '300', '350', '400', '450', '500', '550', '600', '650', '700', '750', '775', '800', '825', '850', '875', '900', '925', '950', '975', '1000'], 'year': '2016', 'month': '03', 'day': '16', 'time': '18:00', 'area': '50.00/-10.00/30.00/10.00'}
2020-10-11 11:12:05,468 INFO Welcome to the CDS
2020-10-11 11:12:05,468 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2020-10-11 11:12:07,625 INFO Request is completed
2020-10-11 11:12:07,626 INFO Downloading http://136.156.132.201/cache-compute-0004/cache/data6/adaptor.mars.internal-1602338016.2728524-23059-19-6f928a98-6190-42f5-a86e-4f97d16bdd40.grib to /data/lxr/insarlab/WEATHER/ERA5/ERA5_N30_N50_W10_E10_20160316_18.grb (1.4M)
2020-10-11 11:12:10,046 INFO Download rate 596.6K/s
INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
open geometry file: geometryRadar.h5
reading incidenceAngle  data from file: ../inputs/geometryRadar.h5 ...
reading height          data from file: ../inputs/geometryRadar.h5 ...
reading latitude        data from file: ../inputs/geometryRadar.h5 ...
reading longitude       data from file: ../inputs/geometryRadar.h5 ...

------------------------------------------------------------------------------
calcualting absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 252
> /home/lxr/software/rsmas_insarV2/3rdparty/PyAPS/pyaps3/objects.py(129)__init__()
-> if self.grib in ('ERA'):
(Pdb) c
> /home/lxr/software/rsmas_insarV2/3rdparty/PyAPS/pyaps3/objects.py(266)getdelay()
-> if self.verb:
(Pdb) c
Traceback (most recent call last):
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 736, in <module>
    main(sys.argv[1:])
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 708, in main
    calculate_delay_timeseries(inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 639, in calculate_delay_timeseries
    tropo_data[i] = get_delay(grib_file, inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 581, in get_delay
    aps_obj.getdelay(pha)
  File "/home/lxr/software/rsmas_insarV2/3rdparty/PyAPS/pyaps3/objects.py", line 266, in getdelay
    if self.verb:
  File "/home/lxr/software/rsmas_insarV2/3rdparty/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2444, in __init__
    "ascending" % i)
ValueError: The points in dimension 1 must be strictly ascending.

Thank you very much!

**Comment by ranneylxr** [comment] 2020-10-11 03:18
Hi @yunjunz:
The commond I used is:
tropo_pyaps3.py -f timeseries_demErr.h5 -g ../inputs/geometryRadar.h5

The full output is:
weather model: ERA5 - dry (hydrostatic) and wet delay
weather directory: /data/lxr/insarlab/WEATHER
output tropospheric delay file: ../inputs/ERA5.h5
output corrected time-series file: timeseries_demErr_ERA5.h5
read dates/time info from file: timeseries_demErr.h5
time of cloest available product: 18:00 UTC

downloading weather model data using PyAPS ...
common file size: 1478520 bytes
number of grib files existed    : 251
number of grib files to download: 1

INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
Downloading 1 of 1: /data/lxr/insarlab/WEATHER/ERA5/ERA5_N30_N50_W10_E10_20160316_18.grb
{'product_type': 'reanalysis', 'format': 'grib', 'variable': ['geopotential', 'temperature', 'specific_humidity'], 'pressure_level': ['1', '2', '3', '5', '7', '10', '20', '30', '50', '70', '100', '125', '150', '175', '200', '225', '250', '300', '350', '400', '450', '500', '550', '600', '650', '700', '750', '775', '800', '825', '850', '875', '900', '925', '950', '975', '1000'], 'year': '2016', 'month': '03', 'day': '16', 'time': '18:00', 'area': '50.00/-10.00/30.00/10.00'}
2020-10-11 11:12:05,468 INFO Welcome to the CDS
2020-10-11 11:12:05,468 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2020-10-11 11:12:07,625 INFO Request is completed
2020-10-11 11:12:07,626 INFO Downloading http://136.156.132.201/cache-compute-0004/cache/data6/adaptor.mars.internal-1602338016.2728524-23059-19-6f928a98-6190-42f5-a86e-4f97d16bdd40.grib to /data/lxr/insarlab/WEATHER/ERA5/ERA5_N30_N50_W10_E10_20160316_18.grb (1.4M)
2020-10-11 11:12:10,046 INFO Download rate 596.6K/s
INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
INFO: You are using the latest ECMWF platform for downloading datasets: https://cds.climate.copernicus.eu/api/v2
open geometry file: geometryRadar.h5
reading incidenceAngle  data from file: ../inputs/geometryRadar.h5 ...
reading height          data from file: ../inputs/geometryRadar.h5 ...
reading latitude        data from file: ../inputs/geometryRadar.h5 ...
reading longitude       data from file: ../inputs/geometryRadar.h5 ...

calcualting absolute delay for each date using PyAPS (Jolivet et al., 2011; 2014) ...
number of grib files used: 252
Traceback (most recent call last):
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 736, in <module>
    main(sys.argv[1:])
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 708, in main
    calculate_delay_timeseries(inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 639, in calculate_delay_timeseries
    tropo_data[i] = get_delay(grib_file, inps)
  File "/home/lxr/software/rsmas_insarV2/sources/MintPy/mintpy/tropo_pyaps3.py", line 581, in get_delay
    aps_obj.getdelay(pha)
  File "/home/lxr/software/rsmas_insarV2/3rdparty/PyAPS/pyaps3/objects.py", line 266, in getdelay
    if self.verb:
  File "/home/lxr/software/rsmas_insarV2/3rdparty/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2444, in __init__
    "ascending" % i)
ValueError: The points in dimension 1 must be strictly ascending

Thank you very much!

**Comment by krasny2k5** [comment] 2021-02-05 15:48
I am having this same problem.

If I can provide any info to debug it please tell me, however i think that @ranneylxr already pinpoint the source of the problem.

**Comment by yunjunz** [comment] 2021-03-02 04:46
Thank you @ranneylxr and @krasny2k5 for identifying the issue. It's rooted from the [scipy.interpolate.RegularGridInterpolator call](https://github.com/yunjunz/PyAPS/blob/main/pyaps3/objects.py#L268), as @ranneylxr has pointed out. I could think of two solutions:

1. If you are sure that your dataset region does not cross the 360/0 boundary, you could add a constraint in [MintPy/tropo_pyaps3.py#L391](https://github.com/insarlab/MintPy/blob/main/mintpy/tropo_pyaps3.py#L391) to not let the SNWE cross it.

2. In `PyAPS/pyaps3/objects.py`, replace all `[lon < 0.] += 360.` with `[lon <= 0.] += 360.`.

I would encourage you to test if option 2 works or not. Or if you could send me your files (timeiseries.h5 and geometryRadar.h5), I could test it when I got a chance (but I cannot promise any timeline for it).

**Comment by pbrotoisworo** [comment] 2021-08-12 07:23
Hello @yunjunz I've tested option 1 and 2. Option 1 works. Option 2 fails.

**Context:**
- My test scene is in London
- I used Hyp3 data that was reprojected to EPSG 4326
- In every test I started from an empty output directory and it downloads the PyAPS GRIB files

subset config I used:
`mintpy.subset.lalo         = 51.358327115205576:51.52535919942483,-0.12744078419785754:0.1733108056463519`

### Option 1:
This is successful and I was able to run the entire smallbaselineApp process. I added a constraint in before the `return` line
https://github.com/insarlab/MintPy/blob/main/mintpy/tropo_pyaps3.py#L407

Very rough implementation:
```python
# If bbox crosses lon0 assume that W is negative
# E should be larger than W but should not cross 0. If it does set to -1.
if (E > W) and (E >= 0):
    E = -1
```

The original W and E values for the bbox are -10 and 10 respectively. After this modification they are -10 and -1
Though I'm not sure if this is the right way to go about it since I'm not sure how this will affect the tropo_pyaps3 process.

### Option 2:
For option 2 I only edited [Line 117](https://github.com/yunjunz/PyAPS/blob/main/pyaps3/objects.py#L117) in `pyaps3/objects.py` according to your suggestion. It still raises the error.

Hopefully this helps.

**Comment by yunjunz** [comment] 2021-08-13 04:29
Thank you @pbrotoisworo for reminding me of this issue. I did not realize this longitude jump is around the UK, which would be pretty common. Fixing it in pyaps would make much more sense. With the commit above, this should be gone now (passed my local testing). 

Let me know if it works for you please, then I will go ahead to close the issue.

**Comment by pbrotoisworo** [comment] 2021-08-13 09:27
Hi @yunjunz. The output seems to be good. There is no more error when downloading new ERA5 data and the visualization in timeseries_ERA5.h5 seems okay.

**Closed** 2021-08-13 17:43 UTC
Labels: pull-request-welcome, good-first-issue
