### ISSUE TITLE
Possibly add python>=3.6 to docs/conda.txt

### ISSUE THREAD

**Issue by piyushrpt** [insarlab/MintPy#83] opened 2019-06-08 06:02 UTC
This is related to #76 

When combining multiple requirements.txt (conda.txt for MintPy) to use gdal  3.0 features  with MintPy, conda's automatic resolution downgrades the python version to 2.7 to satisfy all the requirements. Adding python>=3.6 to conda.txt guarantees that a python3 environment is setup and that python doesnt get accidentally downgraded.

It would help to include this in the requirements file to allow for setup of environments where multiple tools can operate in the same env by just combining the requirements.txt files.

 For reference adding these 3 lines to conda.txt allows us to interoperate with gdal3.0
```
gdal>=3.0
libgdal
python>=3.6
```

**Comment by yunjunz** [comment] 2019-06-08 17:11
Hi @piyushrpt, I have added the 3 lines you suggested to `conda.txt`. Thank you for the recommendation.

**Comment by piyushrpt** [comment] 2019-06-09 04:23
@yunjunz Thanks for the update

**Comment by piyushrpt** [comment] 2019-06-09 22:40
Sorry for reopening the issue. Wanted to add information on conflict between proj.4 (version 6) that is needed for GDAL3 and matplotlib.basemap which needs the older version of (proj.4). This can be overcome by pointing PROJ_LIB to data directory provided by pyproj

```
export PROJ_LIB=`python3 -c "import pyproj; print(pyproj.pyproj_datadir)"`
```

**Comment by piyushrpt** [comment] 2019-06-09 23:24
There exists a minor conflict in handling the PROJ_LIB environment variable by the different packages. 

- For GDAL3, this needs to point to PROJ v6 which is in share/proj. This is automatically done by conda. 
- For basemap to continue to work with older PROJ conventions, this needs to point to 
```
export PROJ_LIB=`python3 -c "import pyproj; print(pyproj.pyproj_datadir)"`
```

For now one might have to toggle between the 2 settings for HDF5 preparation / visualization stages for #76

**Comment by yunjunz** [comment] 2019-06-10 00:29
Thank you @piyushrpt for the suggestion, I have updated the installation note accordingly.

**Comment by hfattahi** [comment] 2019-06-10 18:46
@yunjunz For now let's remove the "gdal>=3.0" from the https://github.com/insarlab/MintPy/blob/master/docs/conda.txt please and leave the issue open until basemap and GDAL3 are consistent (which shouldn't be long). This way we won't break mintpy (in particular basemap) for mintpy users. The solution @piyushrpt gave is clear enough for limited users of prep_aria.py at the moment.

**Comment by yunjunz** [comment] 2019-06-10 19:15
Hi @hfattahi, from a test installation using the current `conda.txt` with `gdal>=3.0` and `PROJ_LIB` setup, `basemap` from MintPy works for me, as shown below.

I did not test `prep_aria.py` and thought `toggle between the 2 settings` meant for `PROJ_LIB` setup only, is it @piyushrpt ?

```
[yunjunz:~] yunjunz% conda list gdal
# packages in environment at /Users/yunjunz/development/python/miniconda3_test:
#
# Name                    Version                   Build  Channel
gdal                      3.0.0            py36h7eb7563_3    conda-forge
libgdal                   3.0.0                h1405c63_3    conda-forge

[yunjunz:~] yunjunz% smallbaselineApp.py -v
MintPy release version v1.1.2-28, release date 2019-06-09

[yunjunz:~] yunjunz% plot_coherence_matrix.py
usage: plot_coherence_matrix.py [-h] [--yx Y X] [--lalo LAT LON]
                                [--lookup LOOKUP_FILE] [-c COLORMAP]
                                [--figsize WID LEN] [--img-file IMG_FILE]
                                [--view-cmd VIEW_CMD] [--save] [--nodisplay]
                                [--noverbose]
                                ifgram_file
plot_coherence_matrix.py: error: the following arguments are required: ifgram_file
```

**Comment by piyushrpt** [comment] 2019-06-10 20:16
That's right. You need PROJ_LIB to point to the default proj6 (setup by activating conda env) for using prep_aria to generate HDF5. Once this is done, one needs to set PROJ_LIB with the command that points to pyproj data for using basemap. Hopefully, this discrepancy in basemap gets resolved soon. Just want to make sure that adding gdal3 is not forcing other users to change their behavior (since everything needed for prep_aria is not public yet).

**Comment by yunjunz** [comment] 2019-06-10 21:16
`PROJ_LIB` problem has existed for a while now for `basemap` https://github.com/conda-forge/basemap-feedstock/issues/30. It's caused by conda installation only, macports installation works fine. Adding `gdal` to conda.txt does not affect this problem.

Related with basemap, I gave a shot on replacing basemap with `cartopy` #87, but not very successful. Will look at it again in the future.

I do agree that `gdal>=3.0` in conda.txt is a relative strong constraint, which might force other users  to change their behavior, and other scripts in mintpy do not need it. I will remove it for now.

**Comment by yunjunz** [comment] 2019-07-23 00:11
The basemap issue seems to be fixed in the link below. But there is no new release since then yet.

https://github.com/matplotlib/basemap/pull/454

**Comment by Ovec8hkin** [comment] 2020-02-07 15:31
Can this be closed now that Basemap has been replaced by cartopy?

**Comment by yunjunz** [comment] 2020-02-07 18:35
From my testing on macOS Mojave, I am able to install isce2, aria-tools, mintpy and pyaps all in one conda environment, with the note here: https://github.com/yunjunz/macOS_Setup/blob/master/README.md. Close this issue.

**Closed** 2020-02-07 18:36 UTC
