### ISSUE TITLE
Error in generate_mask.py

### ISSUE THREAD

**Issue by SMJMirzadeh** [insarlab/MintPy#299] opened 2020-03-11 16:09 UTC
**Description of the problem**

I generated the input files, processed by the ISCE and Envisat dataset, and made a suitable structure compatible with MintPy. When I run the "smallbaselineApp.py" script, I get the following error in the generate_mask.py code. I do really appreciate if you can help me to fix it.

**Full script that generated the error**

**Full error message**

```
generate_mask.py temporalCoherence.h5 -m 0.7 -o maskTempCoh.h5 --base /data2/hbrandon/Sayyed/ASC/inputs/geometryRadar.h5 --base-dataset shadowMask --base-value 1
update mode: ON
run or skip: run
input temporalCoherence file: temporalCoherence.h5
read temporalCoherence.h5
create initial mask with the same size as the input file and all = 1
all pixels with nan value = 0
exclude pixels with value < 0.7
Traceback (most recent call last):
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/smallbaselineApp.py", line 1090, in <module>
    main()
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/smallbaselineApp.py", line 1080, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/smallbaselineApp.py", line 1024, in run
    self.run_network_inversion(sname)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/smallbaselineApp.py", line 551, in run_network_inversion
    self.generate_temporal_coherence_mask()
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/smallbaselineApp.py", line 589, in generate_temporal_coherence_mask
    mintpy.generate_mask.main(scp_args.split())
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/generate_mask.py", line 281, in main
    inps.outfile = create_threshold_mask(inps)
  File "/data2/ssangha/conda_installation/stable_feb14_2020/MintPy/mintpy/generate_mask.py", line 219, in create_threshold_mask
    mask[base_data == float(inps.base_value)] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 5734 but corresponding boolean dimension is 28672
```
[Terminal_Comments.txt](https://github.com/insarlab/MintPy/files/4318908/Terminal_Comments.txt)

**System information**

* Operating system: server-based CentOS
* Version of Python and relevant dependencies if applicable: python 3.7.6
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2.0-20, release date 2020-02-13

**Comment by SMJMirzadeh** [comment] 2020-03-12 02:17
Dear Yunjun,

I can see that something edited by you. Could you please let me know you fixed this issue or I must provide more information here?

Sincerely

**Comment by yunjunz** [comment] 2020-03-18 03:04
Hi @SMJMirzadeh, you could try to find the cause based on the printout information: 1) run `generate_mask.py` command as shown to re-produce the error; 2) check the two related files: temporalCoherence.h5 and geometryRadar.h5 file to see if they are normal and as expected, which you could use the example dataset as reference. 

Check the jupyter notebook example if you are not familiar with the workflow and the paper if you want to know the algorithm.

Always update your code to the latest, always provide as much info as possible, as shown in the guideline.

**Comment by yunjunz** [comment] 2020-04-14 22:16
Close this issue as it's not confirmed and not followed up.

**Closed by yunjunz** 2020-04-14 22:16 UTC

**Comment by alejobeap** [comment] 2021-06-30 11:53
Dear I had the same error 
generate_mask.py /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5 -m 0.7 -o /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/maskTempCoh.h5 --base /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/inputs/geometryRadar.h5 --base-dataset shadowMask --base-value 1
update mode: ON
run or skip: run
input temporalCoherence file: /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5
read /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5
create initial mask with the same size as the input file and all = 1
all pixels with nan value = 0
exclude pixels with value < 0.7
Traceback (most recent call last):
  File "/home/insar/tools/MintPy/mintpy/smallbaselineApp.py", line 1255, in <module>
    main(sys.argv[1:])
  File "/home/insar/tools/MintPy/mintpy/smallbaselineApp.py", line 1237, in main
    app.run(steps=inps.runSteps)
  File "/home/insar/tools/MintPy/mintpy/smallbaselineApp.py", line 1044, in run
    self.run_network_inversion(sname)
  File "/home/insar/tools/MintPy/mintpy/smallbaselineApp.py", line 558, in run_network_inversion
    self.generate_temporal_coherence_mask()
  File "/home/insar/tools/MintPy/mintpy/smallbaselineApp.py", line 596, in generate_temporal_coherence_mask
    mintpy.generate_mask.main(iargs)
  File "/home/insar/tools/MintPy/mintpy/generate_mask.py", line 281, in main
    inps.outfile = create_threshold_mask(inps)
  File "/home/insar/tools/MintPy/mintpy/generate_mask.py", line 219, in create_threshold_mask
    mask[base_data == float(inps.base_value)] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 768 but corresponding boolean dimension is 7683


**I run only the generate_mask.py**
generate_mask.py /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5 -m 0.7 -o /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/maskTempCoh.h5 --base /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/inputs/geometryRadar.h5 --base-dataset shadowMask --base-value 1
input temporalCoherence file: /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5
read /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5
create initial mask with the same size as the input file and all = 1
all pixels with nan value = 0
exclude pixels with value < 0.7
Traceback (most recent call last):
  File "/home/insar/tools/MintPy/mintpy/generate_mask.py", line 290, in <module>
    main(sys.argv[1:])
  File "/home/insar/tools/MintPy/mintpy/generate_mask.py", line 281, in main
    inps.outfile = create_threshold_mask(inps)
  File "/home/insar/tools/MintPy/mintpy/generate_mask.py", line 219, in create_threshold_mask
    mask[base_data == float(inps.base_value)] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 768 but corresponding boolean dimension is 7683

**the information of temporalCoherence.h5 is**
info.py temporalCoherence.h5 
******************** Basic File Info ************************
file name: /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/temporalCoherence.h5
file type: temporalCoherence
coordinates : RADAR

******************** HDF5 File Structure ********************
Attributes in / level:
  ALOOKS                                     1
  ANTENNA_SIDE                               -1
  AZIMUTH_PIXEL_SIZE                         2.001721072513331
  CENTER_INCIDENCE_ANGLE                     39.17796
  CENTER_LINE_UTC                            39592.0
  DATA_TYPE                                  float32
  DATE12                                     200103-200205
  EARTH_RADIUS                               6337170.890775801
  END_DATE                                   20210318
  FILE_LENGTH                                768
  FILE_PATH                                  /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/Igrams/20200103_20200205/filt_20200103_20200205_snaphu.unw
  FILE_TYPE                                  temporalCoherence
  HEADING                                    -168.84096928711756
  HEIGHT                                     511943.35440457455
  ISCE_VERSION                               Release: 2.3, svn-2531, 20190112. Current: svn-Unknown.
  LAT_REF1                                   -1.9963250752662827
  LAT_REF2                                   -1.9429564576008602
  LAT_REF3                                   -2.1226392990244736
  LAT_REF4                                   -2.0685111950161206
  LENGTH                                     768
  LON_REF1                                   -78.16791676434826
  LON_REF2                                   -78.4335881704255
  LON_REF3                                   -78.19140336366478
  LON_REF4                                   -78.46066658718979
  NCORRLOOKS                                 6.092416622076748e-07
  OG_FILE_PATH                               /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/Igrams/20200103_20200205/filt_20200103_20200205_snaphu.unw
  PLATFORM                                   tdx1
  POLARIZATION                               HH
  PRF                                        3841.097059097688
  PROCESSOR                                  isce
  P_BASELINE_BOTTOM_HDR                      226.28813114501745
  P_BASELINE_TOP_HDR                         226.656129175569
  RANGE_PIXEL_SIZE                           1.364105402177116
  REF_X                                      809
  REF_Y                                      220
  RLOOKS                                     1
  STARTING_RANGE                             632152.0430086758
  START_DATE                                 20200103
  UNIT                                       1
  WAVELENGTH                                 0.03106658265798534
  WIDTH                                      1291
  access_mode                                read
  altitude                                   511943.35440457455
  azimuthPixelSize                           2.001721072513331
  azimuthResolution                          2.392
  beam_mode                                  SM
  byte_order                                 l
  data_type                                  float
  earthRadius                                6337170.890775801
  family                                     unwimage
  file_name                                  /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/Igrams/20200103_20200205/filt_20200103_20200205_snaphu.unw
  image_type                                 unw
  length                                     768
  mintpy.networkInversion.maskDataset        False
  mintpy.networkInversion.maskThreshold      0.4
  mintpy.networkInversion.minNormVelocity    True
  mintpy.networkInversion.minRedundancy      1.0
  mintpy.networkInversion.numIfgram          27
  mintpy.networkInversion.obsDatasetName     unwrapPhase
  mintpy.networkInversion.weightFunc         var
  name                                       unwimage_name
  number_bands                               2
  orbitNumber                                52884
  polarization                               HH
  prf                                        3841.097059097688
  radarWavelength                            0.03106658265798534
  rangePixelSize                             1.364105402177116
  rangeResolution                            1873702.8625
  relative_orbit                             None
  scheme                                     BIL
  startUTC                                   2020-01-03 10:59:50.737140
  startingRange                              632152.0430086758
  stopUTC                                    2020-01-03 10:59:54.737038
  trackNumber                                None
  width                                      1291
  xmax                                       1291
  xmin                                       0

HDF5 dataset "/temporalCoherence   ": shape (768, 1291)         , dtype <float32>



**the information of geometryRadar.h5 is**
info.py inputs/geometryRadar.h5 
******************** Basic File Info ************************
file name: /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/inputs/geometryRadar.h5
file type: geometry
coordinates : RADAR

******************** HDF5 File Structure ********************
Attributes in / level:
  ALOOKS                    1
  ANTENNA_SIDE              -1
  AZIMUTH_PIXEL_SIZE        2.001721072513331
  CENTER_INCIDENCE_ANGLE    39.17796
  CENTER_LINE_UTC           39592.0
  DATA_TYPE                 float64
  EARTH_RADIUS              6337170.890775801
  FILE_LENGTH               7683
  FILE_PATH                 /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/merged/geom_master/hgt.rdr
  FILE_TYPE                 geometry
  HEADING                   -168.84096928711756
  HEIGHT                    511943.35440457455
  ISCE_VERSION              Release: 2.3, svn-2531, 20190112. Current: svn-Unknown.
  LAT_REF1                  -1.9963250752662827
  LAT_REF2                  -1.9429564576008602
  LAT_REF3                  -2.1226392990244736
  LAT_REF4                  -2.0685111950161206
  LENGTH                    7683
  LON_REF1                  -78.16791676434826
  LON_REF2                  -78.4335881704255
  LON_REF3                  -78.19140336366478
  LON_REF4                  -78.46066658718979
  NCORRLOOKS                6.092416622076748e-07
  OG_FILE_PATH              /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/merged/geom_master/hgt.rdr
  PLATFORM                  tdx1
  POLARIZATION              HH
  PRF                       3841.097059097688
  PROCESSOR                 isce
  RANGE_PIXEL_SIZE          1.364105402177116
  RLOOKS                    1
  STARTING_RANGE            632152.0430086758
  WAVELENGTH                0.03106658265798534
  WIDTH                     12915
  access_mode               read
  altitude                  511943.35440457455
  azimuthPixelSize          2.001721072513331
  azimuthResolution         2.392
  beam_mode                 SM
  byte_order                l
  data_type                 DOUBLE
  description               ['Pixel-by-pixel height in meters.']
  earthRadius               6337170.890775801
  extra_file_name           /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/merged/geom_master/hgt.rdr.vrt
  family                    image
  file_name                 /mnt/procesamiento/Procesamiento_TX/Sangay/Stack_Descendente_1/merged/geom_master/hgt.rdr
  length                    7683
  name                      image_name
  number_bands              1
  orbitNumber               52884
  polarization              HH
  prf                       3841.097059097688
  radarWavelength           0.03106658265798534
  rangePixelSize            1.364105402177116
  rangeResolution           1873702.8625
  relative_orbit            None
  scheme                    BIP
  startUTC                  2020-01-03 10:59:50.737140
  startingRange             632152.0430086758
  stopUTC                   2020-01-03 10:59:54.737038
  trackNumber               None
  width                     12915
  xmax                      12915
  xmin                      0

HDF5 dataset "/azimuthAngle        ": shape (7683, 12915)       , dtype <float32>
HDF5 dataset "/height              ": shape (7683, 12915)       , dtype <float32>
HDF5 dataset "/incidenceAngle      ": shape (7683, 12915)       , dtype <float32>
HDF5 dataset "/latitude            ": shape (7683, 12915)       , dtype <float32>
HDF5 dataset "/longitude           ": shape (7683, 12915)       , dtype <float32>
HDF5 dataset "/shadowMask          ": shape (7683, 12915)       , dtype <bool>
HDF5 dataset "/slantRangeDistance  ": shape (768, 1291)         , dtype <float32>
HDF5 dataset "/waterMask           ": shape (7683, 12915)       , dtype <bool>


Thanks for your help

Alejo

**Comment by yunjunz** [comment] 2021-06-30 21:12
@alejobeap the geometry datasets do not have the same shape as the interferograms, I guess you might had loaded the full resolution geometry files, instead of the multilooked version.

**Comment by alejobeap** [comment] 2021-06-30 21:51
thanks @yunjunz 
My load input file is:
########## 1. load_data

mintpy.load.processor      = isce  #[isce, aria, snap, gamma, roipac, hyp3], auto for isce
mintpy.load.autoPath       = auto  #[yes / no], auto for no, use pre-defined auto path
mintpy.load.updateMode     = auto  #[yes / no], auto for yes, skip re-loading if HDF5 files are complete
mintpy.load.compression    = auto  #[gzip / lzf / no], auto for no.
---------for ISCE only:
mintpy.load.metaFile       = ./merged/SLC/*/masterShelve/data.dat  #[path of common metadata file for the stack], i.e.: ./reference/IW1.xml, ./referenceShelve/data.dat
mintpy.load.baselineDir    = ./baselines  #[path of the baseline dir], i.e.: ./baselines
##---------interferogram datasets:
mintpy.load.unwFile        = ./Igrams/*/filt_*.unw  #[path pattern of unwrapped interferogram files]
mintpy.load.corFile        = ./Igrams/*/filt_*.cor  #[path pattern of spatial coherence       files]
mintpy.load.connCompFile   = ./Igrams/*/filt_*.unw.conncomp  #[path pattern of connected components    files], optional but recommend
mintpy.load.intFile        = auto  #[path pattern of wrapped interferogram   files], optional
mintpy.load.ionoFile       = auto  #[path pattern of ionospheric delay       files], optional
mintpy.load.magFile        = auto  #[path pattern of interferogram magnitude files], optional
---------offset datasets (optional):
mintpy.load.azOffFile      = auto  #[path pattern of azimuth offset file], optional
mintpy.load.rgOffFile      = auto  #[path pattern of range   offset file], optional
mintpy.load.offSnrFile     = auto  #[path pattern of offset signal-to-noise ratio file], optional
---------geometry datasets:
mintpy.load.demFile        = ./merged/geom_master/hgt.rdr  #[path of DEM file]
mintpy.load.lookupYFile    = ./merged/geom_master/lat.rdr  #[path of latitude /row   /y coordinate file], not required for geocoded data
mintpy.load.lookupXFile    = ./merged/geom_master/lon.rdr  #[path of longitude/column/x coordinate file], not required for geocoded data
mintpy.load.incAngleFile   = ./merged/geom_master/los.rdr  #[path of incidence angle file], optional but recommend
mintpy.load.azAngleFile    = ./merged/geom_master/los.rdr  #[path of azimuth   angle file], optional
mintpy.load.shadowMaskFile = ./merged/geom_master/shadowMask.rdr  #[path of shadow mask file], optional but recommend
mintpy.load.waterMaskFile  = auto  #[path of water  mask file], optional but recommend


or which file do you mean?
Thank you

Alejo

**Comment by alejobeap** [comment] 2021-07-01 02:17
Thanks
I multi look the geometry datasets to the same size of the interferograms. and run ok.

Alejo
